"""
Generate structured Obsidian notes from transcribed text.

No AI API needed — this module provides templates and formatting.
For AI-powered summarization, pass the transcript to your preferred LLM.
"""

import os
from datetime import datetime
from pathlib import Path


def generate_note(
    transcript: str,
    title: str = None,
    source: str = None,
    tags: list = None,
    output_dir: str = None,
    filename: str = None,
) -> str:
    """Generate a structured Obsidian-compatible markdown note.
    
    Args:
        transcript: The transcribed text from the video.
        title: Note title. Auto-generated from first line if not provided.
        source: Video source (URL, author, etc).
        tags: List of tags (without #).
        output_dir: Directory to save the note. If None, returns content only.
        filename: Custom filename. Auto-generated if not provided.
        
    Returns:
        Path to saved note, or note content if output_dir is None.
    """
    if not title:
        # Use first 50 chars of transcript as title
        first_line = transcript.split("\n")[0][:50].strip()
        title = first_line if first_line else "Untitled Video Note"
    
    if tags is None:
        tags = ["视频笔记"]
    
    date_str = datetime.now().strftime("%Y-%m-%d")
    tag_str = " ".join(f"#{t}" for t in tags)
    
    note = f"""# {title}

**来源 / Source**: {source or "Unknown"}
**日期 / Date**: {date_str}
**标签 / Tags**: {tag_str}

---

## 原文转录 / Full Transcript

{transcript}

---

## 笔记 / Notes

> 💡 在这里添加你的笔记和想法
> Add your notes and thoughts here

## 行动项 / Action Items

- [ ] 

---
*Generated by [video-to-brain](https://github.com/LunaAI519/video-to-brain) — 手机发视频，AI变笔记*
"""
    
    if output_dir:
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        if not filename:
            safe_title = "".join(c if c.isalnum() or c in " -_" else "" for c in title)[:50]
            filename = f"{date_str}-{safe_title.strip()}.md"
        filepath = os.path.join(output_dir, filename)
        Path(filepath).write_text(note, encoding="utf-8")
        return filepath
    
    return note


# Pre-defined Obsidian folder mapping
OBSIDIAN_FOLDERS = {
    "学习": "30-知识库",
    "商业": "40-商业",
    "内容": "20-内容工厂",
    "默认": "01-收件箱",
}


def get_obsidian_path(vault_path: str, category: str = "默认") -> str:
    """Get the appropriate Obsidian folder for a category.
    
    Args:
        vault_path: Root path to Obsidian vault.
        category: Content category ('学习', '商业', '内容', '默认').
        
    Returns:
        Full path to the target folder.
    """
    folder = OBSIDIAN_FOLDERS.get(category, OBSIDIAN_FOLDERS["默认"])
    return os.path.join(vault_path, folder)
